# ASN 7575 == AARNET 

language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
install:
  - pip install .
script:
  - peerme -s pdbapi discover -d 7575
  - peerme -s pdbapi generate -d 7575 -t ios.template
  - python setup.py test
